package de.qetz.chess.game.position.direction;

public enum Direction {
  FORWARD,
  RIGHT,
  BACKWARD,
  LEFT,
  RIGHT_UP_DIAGONAL,
  RIGHT_DOWN_DIAGONAL,
  LEFT_DOWN_DIAGONAL,
  LEFT_UP_DIAGONAL,
  KNIGHT_RIGHT_UP,
  KNIGHT_RIGHT_MIDDLE_UP,
  KNIGHT_RIGHT_MIDDLE_DOWN,
  KNIGHT_RIGHT_DOWN,
  KNIGHT_LEFT_DOWN,
  KNIGHT_LEFT_MIDDLE_DOWN,
  KNIGHT_LEFT_MIDDLE_UP,
  KNIGHT_LEFT_UP
}